### ISSUE TITLE
Migrate OpenLineage Airflow Integration to Airflow

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1666]
Tracking the Airflow integration work here.

1. https://github.com/apache/airflow/issues/29669
3. https://github.com/apache/airflow/issues/29676
4. https://github.com/apache/airflow/issues/29671
5. https://github.com/apache/airflow/issues/29672
6. https://github.com/apache/airflow/issues/29670

---------------- Provider Release ?! ----------------
- [x]  https://github.com/apache/airflow/issues/29673
- [x]  https://github.com/apache/airflow/issues/29674
- [x] https://github.com/OpenLineage/OpenLineage/issues/1674
