### ISSUE TITLE
Move Marquez integrations to OpenLineage

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#73]
The [Marquez](https://github.com/MarquezProject/marquez) community is excited to announce that the following integrations will be moved to the wider OpenLineage ecosystem:

* [`marquez-airflow`](https://github.com/MarquezProject/marquez/tree/main/integrations/airflow): A library that integrates Airflow DAGs to emit OpenLineage metadata.
* [`marquez-spark`](https://github.com/MarquezProject/marquez/tree/main/integrations/spark): A spark agent using jvm instrumentation to emit OpenLineage metadata.
* [`marquez-integration-common`](https://github.com/MarquezProject/marquez/tree/main/integrations/common): Shared code across integrations.
* `marquez-dbt-snowflake`: A library that integrates with DBT to emit OpenLineage metadata for Snowflake.
* `marquez-dbt-bigquery`: A library that integrates with DBT to emit OpenLineage metadata for BigQuery.

> Note: You can view the integrations in the Marquez repo under [`marquez/integrations/`](https://github.com/MarquezProject/marquez/tree/main/integrations). Marquez is an official reference implementation of the OpenLineage API and all the integrations adopt the OpenLineage standard.

### Why are the integrations being moved to OpenLineage?

The OpenLineage standard  was influenced  by Marquez's underlying data model (_datasets_, _jobs_, _runs_) while also drawing inspiration from the projects lineage ingestion API. With OpenLineage now a standalone project under [LFAI & Data Foundation](https://lfaidata.foundation), we've decided that now would be the right time to move the integrations over as more and more integrations are being added to the [projects roadmap](https://github.com/OpenLineage/OpenLineage/projects/1) (_Looker_, _Flink_, _Beam_, etc). This would also allow for the OpenLineage community to grow and learn from existing integration implementations, prioritize bug fixes, propose new integrations and changes to the spec, etc. 

### What is the timeline for moving the integrations to OpenLineage?

Below we outline a high-level timeline of moving the integrations to OpenLineage. We encourage everyone to provide feedback and express any concerns you may have by commenting in this issue:

- [x] Release Marquez [`0.16.0`](https://github.com/MarquezProject/marquez/projects/12)
- [x] Move the following integrations from Marquez to OpenLineage:
  - [x]  `marquez-airflow` #93 
  - [x]  `marquez-spark` #96
  - [x]  `marquez-integration-common` #74 
  - [x]  ~`marquez-dbt-snowflake`~ #117
  - [x]  ~`marquez-dbt-bigquery`~ #117
- [ ] Deprecate all integrations in Marquez, then link to the new location in the OpenLineage repo https://github.com/MarquezProject/marquez/pull/1585

Then, going forward, new integrations and improvements will be made by open pull requests against the OpenLineage repo. **Note that during this migration phase, existing Marquez specific functionality and environment variables will be maintained to ensure backwards compatibility. The main difference is that integration packages will get a new name: `openlineage-*` instead of `marquez-*`**.
